name: BestTools
main: KRUNCHSHooT\BestTools\Main
version: 2.1.1
api: 5.0.0
author: KRUNCHSHooT

permissions:
  besttools.use:
    default: true
    description: "allow player to use BestTools"
  besttools.blacklist:
    default: true
    description: "Allow player to blacklist some block"
  besttools.reload:
    default: op
    description: "Allow player to blacklist some block"
  besttools.reset:
    default: op
    description: "Allow Player to Reset Player Database"
  besttools.fastpick:
    default: true
    description: "Allow player to use Fast Pickup Feature"