name: BestTools
main: KRUNCHSHooT\BestTools\Main
version: 1.1.0
api: 4.0.0
author: KRUNCHSHooT

permissions:
    besttools.use:
       default: true
       description: "allow player to use BestTools"
    besttools.blacklist:
       default: true
       description: "Allow player to blacklist some block"
    besttools.fastpick:
       default: true
       description: "Allow player to use Fast Pickup Feature"